In [307]:
def calculate_distance(p, q):
    distance=np.sqrt((float(p[1]) - q[1])**2+(float(p[2]) - q[2])**2)
    return distance

In [308]:
def neighbor_vote(q):
    if q>0.5:
        vote=1
    elif q<0.5:
        vote=0
    else:
        -1
    print vote
    # Is it posssible to have a tie? How would you handle that?
    return vote

In [312]:
def knn_classifier(labeled_points, new_point, k):
    points=labeled_points
    point=new_point
    new=[]
    for y in points:
        l=[]
        for x in y:
            l.append(x)
        l.append(calculate_distance(y,point))
        new.append(l)
    df=pd.DataFrame(new)
    df=df.sort(3)
    df=df.iloc[:k]
    into=sum(df[0])/float(len(df[0]))
    pred=neighbor_vote(into)
    return pred

In [313]:
from sklearn import datasets
import pandas as pd
import numpy as np
from sklearn.cross_validation import train_test_split

# import data
iris = datasets.load_iris()
X = iris.data[:100, :2]  # use the first two features and just the first two classes.
y = iris.target[:100]
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.30, random_state=42)

# Split 70/30 into initial data and new points to classify
training_df = pd.DataFrame({'feature1':X_train[:,0],'feature2':X_train[:,1],'class':y_train})
test_df = pd.DataFrame({'feature1':X_test[:,0],'feature2':X_test[:,1],'class':y_test})

In [314]:
train=np.stack((y_train.T,X_train.T[0],X_train.T[1])).T
k=5
temp=[]
triallist=[]
votes=[]
for a in training_df.index:
    temp=[]
    for b in training_df.iloc[a]:
        temp.append(b)
    triallist.append(temp)
for z in test_df.index:
    l=[]
    for x in test_df.iloc[z]:
        l.append(x)
    votes.append(knn_classifier(triallist,l,k))
test_df

1
1
1
0
0
0
0
1
0
0
0
0
1
0
1
0
1
1
0
0
1
1
0
0
1
0
0
1
0
1

/Users/thomas/anaconda/lib/python2.7/site-packages/ipykernel/__main__.py:12: FutureWarning: sort(columns=....) is deprecated, use sort_values(by=.....)

    class  feature1  feature2
0       1       6.0       2.7
1       1       5.5       2.3
2       1       5.9       3.2
3       0       4.8       3.0
4       0       5.1       3.8
5       0       5.1       3.4
6       0       4.6       3.6
7       1       5.5       2.4
8       0       5.4       3.7
9       0       5.1       3.5
10      0       5.7       3.8
11      0       4.8       3.1
12      1       6.1       2.8
13      0       5.5       4.2
14      1       5.5       2.6
15      0       5.0       3.6
16      1       6.8       2.8
17      1       6.7       3.0
18      0       4.8       3.0
19      0       5.4       3.4
20      1       5.7       2.8
21      1       5.6       3.0
22      0       5.0       3.4
23      0       4.4       3.2
24      1       5.6       2.5
25      0       5.7       4.4
26      0       5.0       3.5
27      1       5.7       2.9
28      0       4.9       3.1
29      1       6.3       2.5

In [69]:
training_df
test_df

    class  feature1  feature2
0       1       6.0       2.7
1       1       5.5       2.3
2       1       5.9       3.2
3       0       4.8       3.0
4       0       5.1       3.8
5       0       5.1       3.4
6       0       4.6       3.6
7       1       5.5       2.4
8       0       5.4       3.7
9       0       5.1       3.5
10      0       5.7       3.8
11      0       4.8       3.1
12      1       6.1       2.8
13      0       5.5       4.2
14      1       5.5       2.6
15      0       5.0       3.6
16      1       6.8       2.8
17      1       6.7       3.0
18      0       4.8       3.0
19      0       5.4       3.4
20      1       5.7       2.8
21      1       5.6       3.0
22      0       5.0       3.4
23      0       4.4       3.2
24      1       5.6       2.5
25      0       5.7       4.4
26      0       5.0       3.5
27      1       5.7       2.9
28      0       4.9       3.1
29      1       6.3       2.5

In [ ]:
""" Iteratively classify new points in test_df, based on the labeled points in training_df, and track your accuracy."""

In [ ]:
""" BONUS: plot the labeled points and an example of a new point being classified."""